def rungame():
  import random
  import time
  import sys
  import worldcup as wc
  import climage
  #all the variables below are for storing images into variables for use later
  mbappe = climage.convert('mbappe.png', is_unicode=True)
  goal = climage.convert('goalpost.png', is_unicode=True)
  woah = climage.convert('8bitball.png', is_unicode=True)
  player = climage.convert('playerkeeper.png', is_unicode=True)
  ai = climage.convert('enemeykeeper.png', is_unicode=True)
  messi = climage.convert('messi.png', is_unicode=True)
  trophy = climage.convert('trophy.png', is_unicode=True)
  speed = climage.convert('speed.png', is_unicode=True)

  while True:
    #All the lists I will use later on 
    directions = ["Upper left", "Upper right", "Middle", "Bottom right", "Bottom left" ]
    countries = ["Japan", "Morocco", "Ecuador", "Qatar", "England"]
    blocking = ["Left", "Right", "Center"]
    #using type write  I print out the start and ask the user to input the num
    wc.type("WARNING: while playing this game, do not try to speed through dialogue, HAVE FUN")
    input()
    wc.type("Mr Beast: Hey guys I am MR BEASTTTTTTTT, welcome to super awesome world cup ")
    input()
    #using the function i made that takes in the integar yo
    country =int(input(wc.type("Mr Beast: What country do you want to play for sonny boy?\n 1. Japan\n 2. Morocco\n 3. Ecuador\n 4. Qatar\n 5. England\n (Type the number of the country you want):")))
    team = wc.listpicker(countries,country)
    print("You will play as foward for " + team + " now")
    input()
    wc.clearConsole()
    print("Your first opponents will be... ")
    input()
    print("PREVIOUS WINNERS FRANCEEEEEEEEEEEE")
    input()
    print(mbappe)
    wc.type("The star striker himself KYLIAN MBAPPEEEEEEEEEEEEEEE will be taking pens for France ")
    input()
    wc.type("A coin is tossed and " + team + " will be taking pens first")
    input()
    wc.clearConsole()
    print(goal)
    wc.type("You take up your position and you wonder... where should I shoot?")
    input()
    shoot = int(input(wc.type("1.Upper left\n2.Upper right\n3. Middle\n4. Bottom right\n5. Bottom left\n(type the number of the direction you want to shoot)")))
    direct = wc.listpicker(directions,shoot)
    wc.type("You chose to shoot in the: " + direct)
    input()
    curve = wc.curv()
    wc.type("Mr Beast: He takes the shot and.....")
    goalie = wc.oppdr(directions)
    input()
    if curve == 7:
      wc.type("Mr Beast: ...\n WHATS THIS? HE PUT CURVE ON THE BALL")
      input()
      print(woah)
      wc.type("Mr Beast: AND WITH THAT CURVE A CLEAN SHOT IS MADEEEEEE")
    if goalie == shoot:
      print(ai)
      wc.type("Mr Beast: ...\n IT IS SAVED BY THE GOALKEEPER WHAT A SAVEEEEEEEE ")
    else:
      print(woah)
      wc.type("Mr Beast: ...\n WHAT A KICK FROM " + team.upper() + "!!! 1 UP FOR THEMMMM")
    input()
    wc.clearConsole()
    print(goal)
    wc.type("Mbappe steps up to the plate... where should I block?")
    input()
    block = int(input(wc.type("1. Left\n2. Right\n3.Center\n (type the number of the direction you want to block:")))
    block = wc.listpicker(blocking,block)
    wc.type("You chose to block: " + block)
    input()
    striker = wc.oppdr(blocking)
    wc.type("Mr Beast: Mbappe takes the shot and.....")
    input()
    if block == striker:
      wc.type("Mr Beast:...\n")
      input()
      print(player)
      wc.type("AND " + team.upper() + " MANAGED TO SAVE ITTTTT THEY GO ON TO THE NEXT ROUND")
      input()
      wc.clearConsole()
    else:
      wc.type("Mr Beast:...\n")
      input()
      print(woah)
      wc.type("Mr Beast: AND MBAPPE STRIKES IT INTO THE CORNER FRANCE IS ALIVEEEEEEE")
      input()
      wc.type("After a tough shootout... " + team +" prevailed and heads to the final")
      input()
      wc.clearConsole()
    print("Your second and oppenents are... ")
    input()
    print("FROM SOUTH AMERICAAAA COMES ARGENTINAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
    input()
    print(messi)
    wc.type("7 time ballon dor winner Lionel Messi will be taking pens for Argentina")
    input()
    wc.type("A coin is tossed and Agrentina will be taking pens first")
    input()
    wc.clearConsole()
    print(goal)
    wc.type("Messi steps up to the plate... where should I block?")
    input()
    block = int(input(wc.type("1. Left\n2. Right\n3.Center\n (type the number of the direction you want to block:")))
    block = wc.listpicker(blocking,block)
    wc.type("You chose to block: " + block)
    input()
    striker = wc.oppdr(blocking)
    wc.type("Mr Beast: Messi takes the shot and.....")
    input()
    if block == striker:
      wc.type("Mr Beast:...\n")
      input()
      print(player)
      wc.type("AND " + team.upper() + " MANAGED TO SAVE ITTTTT THEY CLING ONTO DEAR LIFE")
      input()
      wc.clearConsole()
    else:
      wc.type("Mr Beast:...\n")
      input()
      print(woah)
      wc.type("Mr Beast: AND MESSI ROLLS  IT INTO THE CORNER ARGENTINA REFUSES TO BACK DOWN")
      input()
      wc.clearConsole()
    print(goal)
    wc.type("It is all down to this one last goal, it is do or death.")
    input()
    wc.type("You take up your position and you wonder... where should I shoot?")
    input()
    shoot = int(input(wc.type("1.Upper left\n2.Upper right\n3. Middle\n4. Bottom right\n5. Bottom left\n(type the number of the direction you want to shoot)")))
    direct = wc.listpicker(directions,shoot)
    wc.type("You chose to shoot in the: " + direct)
    input()
    curve = wc.curv()
    wc.type("Mr Beast: He takes the shot and.....")
    goalie = wc.oppdr(directions)
    input()
    if curve == 7:
      wc.type("Mr Beast: ...\n WHATS THIS? HE PUT CURVE ON THE BALL")
      input()
      print(woah)
      wc.type("Mr Beast: AND WITH THAT CURVE A CLEAN SHOT IS MADEEEEEE SHOCKING THE WORLDDDDDD " + team.Upper() + " HAVE WON THE BEAST CUP WOOOOOOOO")
      input()
      wc.clearConsole()
      print(trophy)
      wc.type("looks like your journey is over... would you like to play again? ")
      answer = input("Type yes or no: ").lower()
      if answer == "no":
        wc.type("Mr Beast: see ya next world cup kid")
        input()
        wc.clearConsole()
        print(speed)
        wc.type("Speed: HEY CONGRATS ON WINNING , RONALDO STILL THE GOAT THOUGH, SUIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII")
        exit()
      else:
        continue
    if goalie == shoot:
      print(ai)
      wc.type("Mr Beast: ...\n IT IS SAVED BY THE GOALKEEPER WHAT A SAVEEEEEEEE ")  
      input()
      wc.clearConsole()
      wc.type("The shootout went on for longer and Argentina have won..\n sorry kid maybe next time you will win")
      input()
      exit()
    if curve == 7:
      wc.type("Mr Beast: ...\n WHATS THIS? HE PUT CURVE ON THE BALL")
      input()
      print(woah)
      wc.type("Mr Beast: AND WITH THAT CURVE A CLEAN SHOT IS MADEEEEEE SHOCKING THE WORLDDDDDD " + team.Upper() + " HAVE WON THE BEAST CUP WOOOOOOOO")
      input()
      wc.clearConsole()
      print(trophy)
      wc.type("looks like your journey is over... would you like to play again? ")
      answer = input("Type yes or no: ").lower()
      if answer == "no":
        wc.type("Mr Beast: see ya next world cup kid")
        input()
        wc.clearConsole()
        print(speed)
        wc.type("Speed: HEY CONGRATS ON WINNING , RONALDO STILL THE GOAT THOUGH, SUIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII")
        exit()
        break
      else:
        continue
    else:
      print(woah)
      wc.type("Mr Beast: ...\n WHAT A KICK FROM " + team.upper() + "!!! THEY HAVE SHOCKED THE ENTIRE WORLD AND HAVE WON THE BEAST CUPPPPPPP!!!")
      input()
      wc.clearConsole
      print(trophy)
    wc.type("looks like your journey is over... would you like to play again? ")
    answer = input("Type yes or no: ").lower()
    if answer == "no":
      wc.type("Mr Beast: see ya next world cup kid")
      input()
      wc.clearConsole()
      print(speed)
      wc.type("Speed: HEY CONGRATS ON WINNING , RONALDO STILL THE GOAT THOUGH, SUIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII")
      break
    else:
      continue
  